# **Basics of numpy and pandas**

**Numpy**

In [ ]:
import numpy as np

n1=np.array([10,20,30,40])   #1D array
print(n1)

n2=np.array([[10,20,30,40],[1,2,3,4]])   #multidimensional array
print(n2)

[10 20 30 40]
[[10 20 30 40]
 [ 1  2  3  4]]


In [ ]:
#initialising numpy with zeroes

n1=np.zeros((5,5))
print(n1)




[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#initialising numpy with one particular value
n1=np.full((2,2),10)
n1

array([[10, 10],
       [10, 10]])

In [ ]:
#initializing numpy array within the range

n1=np.arange(10,20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
#initializing numpy array within the range with specific interval in between

n1=np.arange(10,50,5)   #10 to 50 with a gap of 5 in between
n1

array([10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
#initializing numpy arrays with random numbers

n1=np.random.randint(1,100,5)  #any  5 nos between 1 to 100
n1

array([ 2, 46, 26,  7,  4])

In [ ]:
#checking the shape of numpy arrays

n2=np.array([[10,20,30,40],[1,2,3,4]])
print(n2.shape)


n3=np.array([[10,20,30,40],[1,2,3,4],[6,3,4,5]])
print(n3.shape)


(2, 4)
(3, 4)


In [ ]:
#converting the shape of matrix by altering shape



n2=np.array([[10,20,30,40],[1,2,3,4]])
print(n2.shape)

n2.shape=(4,2)
print(n2)


n2.shape=(8,1)
print(n2)

(2, 4)
[[10 20]
 [30 40]
 [ 1  2]
 [ 3  4]]
[[10]
 [20]
 [30]
 [40]
 [ 1]
 [ 2]
 [ 3]
 [ 4]]


In [ ]:
#joining two numpy arrays

n1=np.array([10,20,30,40])
n2=np.array([1,2,3,4])
np.vstack((n1,n2))  #for vertical stacking



array([[10, 20, 30, 40],
       [ 1,  2,  3,  4]])

In [ ]:
np.hstack((n1,n2))  #for horizontal stacking


array([10, 20, 30, 40,  1,  2,  3,  4])

In [ ]:
np.column_stack((n1,n2))  #for column stacking

array([[10,  1],
       [20,  2],
       [30,  3],
       [40,  4]])

In [ ]:
np.row_stack((n1,n2))  #for row stacking

array([[10, 20, 30, 40],
       [ 1,  2,  3,  4]])

In [ ]:
#Numpy math function

np.std(n1)   #for standard deviation

11.180339887498949

In [ ]:
np.mean(n1)   #for mean of a array

25.0

In [ ]:
np.median(n1)   #for median of a array

25.0

In [ ]:
#Numpy array mathematical opeartions
n1=np.array([10,20,30,40])
n2=np.array([1,2,3,4])
np.sum([n1,n2])  #for normal sum


110

In [ ]:
#for only column addition

np.sum([n1,n2],axis=0)

SyntaxError: ignored